"""沟通留档与德育活动的表声明：家访、谈话、班会、班级活动、大事记、矛盾调解。

词表照旧应用的 `CFG_*` 逐字搬。六张表都声明 `media_owner=True` ——
照片与录音归档统一走媒体库（旧应用是各写各的图片字段，`meetings.images` 与种子里的
`events.photo` 还对不上，老照片接不过来）。
"""

from __future__ import annotations

from app.models.communication import (
    ACTIVITY_TYPES,
    CONFLICT_LEVELS,
    CONFLICT_STATUSES,
    EVENT_CATEGORIES,
    TALK_PLACES,
    TALK_TYPES,
    ClassActivity,
    ClassEvent,
    Conflict,
    Meeting,
    Talk,
    Visit,
)
from app.schemas.table_spec import ColumnSpec, FieldSpec, TableSpec
from app.services.communication_service import (
    apply_conflict_with_date,
    apply_default_date,
    apply_meeting_with_date,
    link_talk_student_with_date,
    link_visit_student_with_date,
)

VISIT = TableSpec(
    key="visits",
    title="家访记录",
    entity="家访",
    model=Visit,
    columns=(
        ColumnSpec("date", "日期", w="104px", numeric=True),
        ColumnSpec("student_name", "学生", w="100px"),
        ColumnSpec("teacher", "家访教师", w="110px"),
        ColumnSpec("duration", "时长", w="80px"),
        ColumnSpec("consensus", "达成共识"),
    ),
    fields=(
        FieldSpec("date", "家访日期", type="date", hint="留空按今天"),
        FieldSpec("student_name", "学生", required=True),
        FieldSpec("teacher", "家访教师", hint="如 王老师 / 班主任"),
        FieldSpec("duration", "家访时长", hint="如 40 分钟"),
        FieldSpec(
            "home_situation",
            "家庭情况观察",
            type="textarea",
            full=True,
            hint="居住环境、家庭成员、亲子关系等",
        ),
        FieldSpec("performance", "学生在家表现", type="textarea", full=True),
        FieldSpec("parent_needs", "家长诉求与关切", type="textarea", full=True),
        FieldSpec(
            "consensus",
            "达成的共识",
            type="textarea",
            full=True,
            hint="如 家校在手机管理上达成一致",
        ),
        FieldSpec("note", "备注", type="textarea", full=True),
    ),
    search_keys=("student_name", "teacher", "consensus", "parent_needs"),
    filter_keys=("teacher",),
    default_sort=("date", -1),
    dedupe_keys=("date", "student_name", "teacher"),
    extra_keys=("student_id", "sno"),
    media_owner=True,
    before_save=link_visit_student_with_date,
)

TALK = TableSpec(
    key="talks",
    title="学生谈话",
    entity="谈话",
    model=Talk,
    columns=(
        ColumnSpec("date", "日期", w="104px", numeric=True),
        ColumnSpec("student_name", "学生", w="100px"),
        ColumnSpec("type", "类型", w="96px"),
        ColumnSpec("reason", "谈话缘由", w="200px"),
        ColumnSpec("content", "谈话过程"),
        ColumnSpec("result", "谈话结果", w="190px", sortable=False),
        ColumnSpec("follow_up", "跟进安排", w="150px", sortable=False),
        ColumnSpec("place", "地点", w="88px"),
    ),
    fields=(
        FieldSpec("date", "谈话日期", type="date", hint="留空按今天"),
        FieldSpec("student_name", "学生", required=True),
        FieldSpec("type", "谈话类型", type="select", options=TALK_TYPES, default="学业指导"),
        FieldSpec("place", "谈话地点", type="select", options=TALK_PLACES, default="办公室"),
        FieldSpec(
            "reason",
            "谈话缘由",
            required=True,
            full=True,
            hint="如 月考数学从 118 分降至 92 分",
        ),
        FieldSpec("content", "谈话过程与内容", type="textarea", required=True, full=True),
        FieldSpec("result", "谈话结果", type="textarea", full=True),
        FieldSpec("follow_up", "跟进安排", full=True, hint="如 两周后回访"),
        FieldSpec("recorder", "谈话教师"),
    ),
    search_keys=("student_name", "type", "reason", "content", "result"),
    filter_keys=("type", "place"),
    default_sort=("date", -1),
    dedupe_keys=("date", "student_name", "type"),
    extra_keys=("student_id", "sno"),
    media_owner=True,
    before_save=link_talk_student_with_date,
)

MEETING = TableSpec(
    key="meetings",
    title="主题班会",
    entity="班会",
    model=Meeting,
    columns=(
        ColumnSpec("date", "日期", w="104px", numeric=True),
        ColumnSpec("theme", "班会主题", w="220px"),
        ColumnSpec("host", "主持人", w="96px"),
        ColumnSpec("content", "组织过程"),
        ColumnSpec("effect", "育人成效", w="220px", sortable=False),
        ColumnSpec("attend_text", "出席", w="76px", sortable=False),
    ),
    fields=(
        FieldSpec("date", "召开日期", type="date", hint="留空按今天"),
        FieldSpec("theme", "班会主题", required=True, hint="如 诚信考试主题教育"),
        FieldSpec("host", "主持人", hint="如 班主任 / 团支书"),
        FieldSpec(
            "attend_actual",
            "实到人数",
            type="number",
            hint="旧版是一个「45/45」的文本框，统计不出来；这里有应到时不能超过它",
        ),
        FieldSpec("attend_expected", "应到人数", type="number"),
        FieldSpec("content", "组织过程与主要内容", type="textarea", required=True, full=True),
        FieldSpec("effect", "育人成效与后续", type="textarea", full=True),
    ),
    search_keys=("theme", "content", "host", "effect"),
    filter_keys=("host",),
    default_sort=("date", -1),
    dedupe_keys=("date", "theme"),
    extra_keys=("attend_text",),
    media_owner=True,
    before_save=apply_meeting_with_date,
)

ACTIVITY = TableSpec(
    key="class_activities",
    title="班级活动",
    entity="活动",
    model=ClassActivity,
    columns=(
        ColumnSpec("date", "日期", w="104px", numeric=True),
        ColumnSpec("title", "活动主题", w="220px"),
        ColumnSpec("type", "类型", w="120px"),
        ColumnSpec("organizer", "组织者", w="110px"),
        ColumnSpec("content", "活动过程"),
        ColumnSpec("effect", "活动成效", w="200px", sortable=False),
        ColumnSpec("place", "地点", w="120px"),
    ),
    fields=(
        FieldSpec("date", "活动日期", type="date", hint="留空按今天"),
        FieldSpec("title", "活动主题", required=True, hint="如 春季趣味运动会"),
        FieldSpec("type", "活动类型", type="select", options=ACTIVITY_TYPES),
        FieldSpec("organizer", "组织者", hint="如 班委 / 团支部"),
        FieldSpec("place", "活动地点", hint="如 学校操场 / 社区中心"),
        FieldSpec("content", "活动过程与主要内容", type="textarea", required=True, full=True),
        FieldSpec("effect", "活动成效与反响", type="textarea", full=True),
    ),
    search_keys=("title", "content", "organizer", "place"),
    filter_keys=("type",),
    default_sort=("date", -1),
    dedupe_keys=("date", "title"),
    media_owner=True,
    before_save=apply_default_date,
)

EVENT = TableSpec(
    key="class_events",
    title="班级大事记",
    entity="大事记",
    model=ClassEvent,
    columns=(
        ColumnSpec("date", "日期", w="104px", numeric=True),
        ColumnSpec("title", "事件", w="250px"),
        ColumnSpec("category", "类别", w="76px"),
        ColumnSpec("content", "详细内容"),
        ColumnSpec("participants", "参与者", w="118px"),
    ),
    fields=(
        FieldSpec("date", "发生日期", type="date", hint="留空按今天"),
        FieldSpec("title", "事件标题", required=True, hint="如 期中考试班级平均分年级第一"),
        FieldSpec("category", "类别", type="select", options=EVENT_CATEGORIES, default="活动"),
        FieldSpec("participants", "参与者", default="全班", hint="如 全班 / 宣传组 6 人"),
        FieldSpec("content", "详细内容", type="textarea", required=True, full=True),
    ),
    search_keys=("title", "content", "category", "participants"),
    filter_keys=("category",),
    default_sort=("date", -1),
    dedupe_keys=("date", "title"),
    extra_keys=("honored",),
    media_owner=True,
    before_save=apply_default_date,
)

CONFLICT = TableSpec(
    key="conflicts",
    title="学生矛盾解决",
    entity="矛盾调解",
    model=Conflict,
    columns=(
        ColumnSpec("date", "日期", w="104px", numeric=True),
        ColumnSpec("parties_cache", "涉及学生", w="150px"),
        ColumnSpec("reason", "矛盾类型", w="150px"),
        ColumnSpec("detail", "起因经过"),
        ColumnSpec("result", "调解结果", w="220px", sortable=False),
        ColumnSpec("level", "程度", w="82px"),
        ColumnSpec("status", "状态", w="82px"),
        ColumnSpec("mediator", "调解人", w="88px"),
    ),
    fields=(
        FieldSpec("date", "发生日期", type="date", hint="留空按今天"),
        FieldSpec(
            "parties_text",
            "涉及学生",
            required=True,
            full=True,
            hint="多人用顿号分隔，如 张三、李四；认不出的学生会报错",
        ),
        FieldSpec("reason", "矛盾类型", required=True, hint="如 宿舍作息冲突"),
        FieldSpec("level", "严重程度", type="select", options=CONFLICT_LEVELS, default="一般"),
        FieldSpec("status", "处理状态", type="select", options=CONFLICT_STATUSES, default="跟踪中"),
        FieldSpec("mediator", "调解人"),
        FieldSpec("detail", "起因与经过", type="textarea", required=True, full=True),
        FieldSpec(
            "process",
            "调解过程",
            type="textarea",
            required=True,
            full=True,
            hint="如：分别单独了解诉求 → 组织面对面沟通 → 共同制定公约",
        ),
        FieldSpec("result", "调解结果", type="textarea", full=True),
        FieldSpec("follow_up", "回访安排", full=True, hint="如 一周后回访，确认宿舍氛围"),
    ),
    search_keys=("parties_cache", "reason", "detail", "process", "result"),
    filter_keys=("level", "status"),
    default_sort=("date", -1),
    dedupe_keys=("date", "parties_cache", "reason"),
    extra_keys=("parties_cache", "resolved"),
    media_owner=True,
    before_save=apply_conflict_with_date,
)
