"""exam exam_subject score

Revision ID: 1876e9d1b47f
Revises: b9f947e712b1
Create Date: 2026-09-18 14:37:40.093988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1876e9d1b47f'
down_revision: Union[str, Sequence[str], None] = 'b9f947e712b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_exams_class_id_classes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exams'))
    )
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exams_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exams_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_exams_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('exam_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=16), nullable=False),
    sa.Column('full_marks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_exam_subjects_exam_id_exams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_subjects')),
    sa.UniqueConstraint('exam_id', 'subject', name='uq_exam_subjects_exam_subject')
    )
    with op.batch_alter_table('exam_subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_subjects_exam_id'), ['exam_id'], unique=False)

    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('absent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_scores_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_scores_exam_id_exams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_scores_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scores')),
    sa.UniqueConstraint('exam_id', 'student_id', 'subject', name='uq_scores_exam_student_subject')
    )
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scores_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scores_student_id'))
        batch_op.drop_index(batch_op.f('ix_scores_exam_id'))
        batch_op.drop_index(batch_op.f('ix_scores_class_id'))

    op.drop_table('scores')
    with op.batch_alter_table('exam_subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_subjects_exam_id'))

    op.drop_table('exam_subjects')
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exams_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_exams_date'))
        batch_op.drop_index(batch_op.f('ix_exams_class_id'))

    op.drop_table('exams')
    # ### end Alembic commands ###
