"""media and contact logs

Revision ID: 2008dc6034ef
Revises: e3dfd6e7dd0e
Create Date: 2026-09-18 15:25:27.826319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2008dc6034ef'
down_revision: Union[str, Sequence[str], None] = 'e3dfd6e7dd0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('owner_table', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('rel_path', sa.String(length=255), nullable=False),
    sa.Column('mime', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('playable', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_media_class_id_classes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media'))
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index('ix_media_owner', ['owner_table', 'owner_id'], unique=False)

    op.create_table('contact_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('student_name', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('result', sa.String(length=8), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('needs_follow_up', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_contact_logs_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_contact_logs_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_logs'))
    )
    with op.batch_alter_table('contact_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_logs_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_logs_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_logs_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_logs_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_logs_student_id'))
        batch_op.drop_index(batch_op.f('ix_contact_logs_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_contact_logs_date'))
        batch_op.drop_index(batch_op.f('ix_contact_logs_class_id'))

    op.drop_table('contact_logs')
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index('ix_media_owner')
        batch_op.drop_index(batch_op.f('ix_media_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_media_class_id'))

    op.drop_table('media')
    # ### end Alembic commands ###
