"""communication logs

Revision ID: 2061fbdebea2
Revises: a1694cc8bc5e
Create Date: 2026-09-18 15:43:57.828878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2061fbdebea2'
down_revision: Union[str, Sequence[str], None] = 'a1694cc8bc5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('organizer', sa.String(length=32), nullable=False),
    sa.Column('place', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('effect', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_class_activities_class_id_classes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_activities'))
    )
    with op.batch_alter_table('class_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_activities_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_activities_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_activities_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('class_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=8), nullable=False),
    sa.Column('participants', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_class_events_class_id_classes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_events'))
    )
    with op.batch_alter_table('class_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_events_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_events_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_events_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('mediator', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('process', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('follow_up', sa.Text(), nullable=False),
    sa.Column('parties_cache', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_conflicts_class_id_classes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conflicts'))
    )
    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conflicts_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conflicts_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_conflicts_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('theme', sa.String(length=64), nullable=False),
    sa.Column('host', sa.String(length=32), nullable=False),
    sa.Column('attend_actual', sa.Integer(), nullable=True),
    sa.Column('attend_expected', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('effect', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_meetings_class_id_classes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meetings'))
    )
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meetings_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meetings_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_meetings_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('conflict_parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conflict_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('student_name', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conflict_id'], ['conflicts.id'], name=op.f('fk_conflict_parties_conflict_id_conflicts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_conflict_parties_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conflict_parties'))
    )
    with op.batch_alter_table('conflict_parties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conflict_parties_conflict_id'), ['conflict_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conflict_parties_student_id'), ['student_id'], unique=False)

    op.create_table('talks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('student_name', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('place', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('follow_up', sa.Text(), nullable=False),
    sa.Column('recorder', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_talks_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_talks_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_talks'))
    )
    with op.batch_alter_table('talks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_talks_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_talks_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_talks_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_talks_student_id'), ['student_id'], unique=False)

    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('student_name', sa.String(length=32), nullable=False),
    sa.Column('teacher', sa.String(length=32), nullable=False),
    sa.Column('duration', sa.String(length=16), nullable=False),
    sa.Column('home_situation', sa.Text(), nullable=False),
    sa.Column('performance', sa.Text(), nullable=False),
    sa.Column('parent_needs', sa.Text(), nullable=False),
    sa.Column('consensus', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_visits_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_visits_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visits'))
    )
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visits_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visits_student_id'))
        batch_op.drop_index(batch_op.f('ix_visits_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_visits_date'))
        batch_op.drop_index(batch_op.f('ix_visits_class_id'))

    op.drop_table('visits')
    with op.batch_alter_table('talks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_talks_student_id'))
        batch_op.drop_index(batch_op.f('ix_talks_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_talks_date'))
        batch_op.drop_index(batch_op.f('ix_talks_class_id'))

    op.drop_table('talks')
    with op.batch_alter_table('conflict_parties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conflict_parties_student_id'))
        batch_op.drop_index(batch_op.f('ix_conflict_parties_conflict_id'))

    op.drop_table('conflict_parties')
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meetings_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_meetings_date'))
        batch_op.drop_index(batch_op.f('ix_meetings_class_id'))

    op.drop_table('meetings')
    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conflicts_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_conflicts_date'))
        batch_op.drop_index(batch_op.f('ix_conflicts_class_id'))

    op.drop_table('conflicts')
    with op.batch_alter_table('class_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_events_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_class_events_date'))
        batch_op.drop_index(batch_op.f('ix_class_events_class_id'))

    op.drop_table('class_events')
    with op.batch_alter_table('class_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_activities_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_class_activities_date'))
        batch_op.drop_index(batch_op.f('ix_class_activities_class_id'))

    op.drop_table('class_activities')
    # ### end Alembic commands ###
