"""dorm duties

Revision ID: 20daa5e4b541
Revises: 6c37e24a99a6
Create Date: 2026-09-18 15:09:49.073368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20daa5e4b541'
down_revision: Union[str, Sequence[str], None] = '6c37e24a99a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dorm_duties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.String(length=8), nullable=False),
    sa.Column('weekday_no', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('student_name', sa.String(length=32), nullable=False),
    sa.Column('task', sa.String(length=32), nullable=False),
    sa.Column('checker', sa.String(length=32), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_dorm_duties_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['dorm_rooms.id'], name=op.f('fk_dorm_duties_room_id_dorm_rooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_dorm_duties_student_id_students'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dorm_duties'))
    )
    with op.batch_alter_table('dorm_duties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dorm_duties_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dorm_duties_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_dorm_duties_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dorm_duties_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dorm_duties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dorm_duties_student_id'))
        batch_op.drop_index(batch_op.f('ix_dorm_duties_room_id'))
        batch_op.drop_index(batch_op.f('ix_dorm_duties_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_dorm_duties_class_id'))

    op.drop_table('dorm_duties')
    # ### end Alembic commands ###
