"""dorm rooms and beds

Revision ID: 3e2246af2e79
Revises: 1876e9d1b47f
Create Date: 2026-09-18 14:54:43.311078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e2246af2e79'
down_revision: Union[str, Sequence[str], None] = '1876e9d1b47f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dorm_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('building', sa.String(length=32), nullable=False),
    sa.Column('room_no', sa.String(length=16), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_dorm_rooms_class_id_classes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dorm_rooms')),
    sa.UniqueConstraint('class_id', 'building', 'room_no', name='uq_dorm_rooms_class_building_room')
    )
    with op.batch_alter_table('dorm_rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dorm_rooms_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dorm_rooms_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('dorm_beds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('bed_no', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('student_name', sa.String(length=32), nullable=False),
    sa.Column('leader', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_dorm_beds_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['dorm_rooms.id'], name=op.f('fk_dorm_beds_room_id_dorm_rooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_dorm_beds_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dorm_beds')),
    sa.UniqueConstraint('room_id', 'bed_no', name='uq_dorm_beds_room_bed')
    )
    with op.batch_alter_table('dorm_beds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dorm_beds_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dorm_beds_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dorm_beds_student_id'), ['student_id'], unique=False)
        batch_op.create_index('uq_dorm_beds_student', ['class_id', 'student_id'], unique=True, sqlite_where=sa.text('student_id IS NOT NULL'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dorm_beds', schema=None) as batch_op:
        batch_op.drop_index('uq_dorm_beds_student', sqlite_where=sa.text('student_id IS NOT NULL'))
        batch_op.drop_index(batch_op.f('ix_dorm_beds_student_id'))
        batch_op.drop_index(batch_op.f('ix_dorm_beds_room_id'))
        batch_op.drop_index(batch_op.f('ix_dorm_beds_class_id'))

    op.drop_table('dorm_beds')
    with op.batch_alter_table('dorm_rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dorm_rooms_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_dorm_rooms_class_id'))

    op.drop_table('dorm_rooms')
    # ### end Alembic commands ###
