"""schedule and countdown

Revision ID: 4ef67dd12eb4
Revises: 8e1cb838c77b
Create Date: 2026-09-18 15:57:56.000239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ef67dd12eb4'
down_revision: Union[str, Sequence[str], None] = '8e1cb838c77b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countdowns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_countdowns_class_id_classes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_countdowns'))
    )
    with op.batch_alter_table('countdowns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_countdowns_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_countdowns_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_countdowns_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('schedule_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.String(length=8), nullable=False),
    sa.Column('weekday_no', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=8), nullable=False),
    sa.Column('subject', sa.String(length=16), nullable=False),
    sa.Column('teacher', sa.String(length=32), nullable=False),
    sa.Column('room', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_schedule_slots_class_id_classes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_slots')),
    sa.UniqueConstraint('class_id', 'weekday_no', 'period', name='uq_schedule_slots_cell')
    )
    with op.batch_alter_table('schedule_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_slots_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_slots_deleted_at'), ['deleted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_slots_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_schedule_slots_class_id'))

    op.drop_table('schedule_slots')
    with op.batch_alter_table('countdowns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_countdowns_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_countdowns_date'))
        batch_op.drop_index(batch_op.f('ix_countdowns_class_id'))

    op.drop_table('countdowns')
    # ### end Alembic commands ###
