"""seat plans and seats

Revision ID: 6c37e24a99a6
Revises: 3e2246af2e79
Create Date: 2026-09-18 15:01:46.501795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c37e24a99a6'
down_revision: Union[str, Sequence[str], None] = '3e2246af2e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seat_plans',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('cols', sa.Integer(), nullable=False),
    sa.Column('rule', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_seat_plans_class_id_classes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('class_id', name=op.f('pk_seat_plans'))
    )
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('col', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('student_name', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_seats_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_seats_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seats')),
    sa.UniqueConstraint('class_id', 'row', 'col', name='uq_seats_class_position')
    )
    with op.batch_alter_table('seats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seats_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seats_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_seats_student_id'), ['student_id'], unique=False)
        batch_op.create_index('uq_seats_student', ['class_id', 'student_id'], unique=True, sqlite_where=sa.text('student_id IS NOT NULL'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seats', schema=None) as batch_op:
        batch_op.drop_index('uq_seats_student', sqlite_where=sa.text('student_id IS NOT NULL'))
        batch_op.drop_index(batch_op.f('ix_seats_student_id'))
        batch_op.drop_index(batch_op.f('ix_seats_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_seats_class_id'))

    op.drop_table('seats')
    op.drop_table('seat_plans')
    # ### end Alembic commands ###
