"""class fees

Revision ID: 8e1cb838c77b
Revises: 2061fbdebea2
Create Date: 2026-09-18 15:49:32.141359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e1cb838c77b'
down_revision: Union[str, Sequence[str], None] = '2061fbdebea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_fee_categories_class_id_classes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fee_categories'))
    )
    with op.batch_alter_table('fee_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_categories_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_categories_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('fee_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('item', sa.String(length=64), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['fee_categories.id'], name=op.f('fk_fee_ledger_category_id_fee_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_fee_ledger_class_id_classes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fee_ledger'))
    )
    with op.batch_alter_table('fee_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_ledger_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_ledger_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_ledger_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_ledger_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('fee_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('student_name', sa.String(length=32), nullable=False),
    sa.Column('should_pay_cents', sa.Integer(), nullable=False),
    sa.Column('paid_cents', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('note', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['fee_categories.id'], name=op.f('fk_fee_records_category_id_fee_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_fee_records_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_fee_records_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fee_records'))
    )
    with op.batch_alter_table('fee_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_records_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_records_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_records_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_records_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_records_student_id'))
        batch_op.drop_index(batch_op.f('ix_fee_records_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_fee_records_class_id'))
        batch_op.drop_index(batch_op.f('ix_fee_records_category_id'))

    op.drop_table('fee_records')
    with op.batch_alter_table('fee_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_ledger_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_fee_ledger_date'))
        batch_op.drop_index(batch_op.f('ix_fee_ledger_class_id'))
        batch_op.drop_index(batch_op.f('ix_fee_ledger_category_id'))

    op.drop_table('fee_ledger')
    with op.batch_alter_table('fee_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_categories_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_fee_categories_class_id'))

    op.drop_table('fee_categories')
    # ### end Alembic commands ###
