"""duty members cache

Revision ID: a1694cc8bc5e
Revises: db25d47805e4
Create Date: 2026-09-18 15:40:03.612272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1694cc8bc5e'
down_revision: Union[str, Sequence[str], None] = 'db25d47805e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('duty_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('members_cache', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('duty_groups', schema=None) as batch_op:
        batch_op.drop_column('members_cache')

    # ### end Alembic commands ###
