"""students / student_field_def / guardians

Revision ID: ab3a5f999d80
Revises: bfb713ac3b7c
Create Date: 2026-09-18 14:11:39.302935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab3a5f999d80'
down_revision: Union[str, Sequence[str], None] = 'bfb713ac3b7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_field_def',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('identity', sa.Boolean(), nullable=False),
    sa.Column('in_list', sa.Boolean(), nullable=False),
    sa.Column('in_form', sa.Boolean(), nullable=False),
    sa.Column('in_detail', sa.Boolean(), nullable=False),
    sa.Column('searchable', sa.Boolean(), nullable=False),
    sa.Column('filterable', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('hint', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_field_def')),
    sa.UniqueConstraint('key', name=op.f('uq_student_field_def_key'))
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('sno', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_students_class_id_classes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students'))
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index('uq_students_class_sno', ['class_id', 'sno'], unique=True, sqlite_where=sa.text("sno <> ''"))

    op.create_table('guardians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('job', sa.String(length=32), nullable=False),
    sa.Column('wechat', sa.String(length=64), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_guardians_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_guardians_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guardians'))
    )
    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guardians_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guardians_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_guardians_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guardians_student_id'))
        batch_op.drop_index(batch_op.f('ix_guardians_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_guardians_class_id'))

    op.drop_table('guardians')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index('uq_students_class_sno', sqlite_where=sa.text("sno <> ''"))
        batch_op.drop_index(batch_op.f('ix_students_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_students_class_id'))

    op.drop_table('students')
    op.drop_table('student_field_def')
    # ### end Alembic commands ###
