"""todos: drop unused done_at column

Revision ID: bfb713ac3b7c
Revises: 990c3d4ca5bc
Create Date: 2026-09-18 14:06:22.480963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfb713ac3b7c'
down_revision: Union[str, Sequence[str], None] = '990c3d4ca5bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_column('done_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('done_at', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
