"""courses and course scores

Revision ID: c84366825226
Revises: 4ef67dd12eb4
Create Date: 2026-09-18 16:07:04.301969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c84366825226'
down_revision: Union[str, Sequence[str], None] = '4ef67dd12eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=16), nullable=False),
    sa.Column('teacher', sa.String(length=32), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses'))
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('course_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=64), nullable=False),
    sa.Column('head_teacher', sa.String(length=32), nullable=False),
    sa.Column('head_teacher_phone', sa.String(length=32), nullable=False),
    sa.Column('representative', sa.String(length=32), nullable=False),
    sa.Column('rep_phone', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_course_classes_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_classes_course_id_courses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_classes'))
    )
    with op.batch_alter_table('course_classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_classes_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_classes_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_classes_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index('uq_course_classes_course_class', ['course_id', 'class_id'], unique=True, sqlite_where=sa.text('deleted_at IS NULL'))

    op.create_table('course_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=32), nullable=False),
    sa.Column('exam_name', sa.String(length=64), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('full_marks', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_course_scores_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_scores_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_course_scores_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_scores'))
    )
    with op.batch_alter_table('course_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_scores_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_scores_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_scores_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_scores_exam_date'), ['exam_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_scores_exam_name'), ['exam_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_scores_student_id'), ['student_id'], unique=False)
        batch_op.create_index('uq_course_scores_exam_student', ['course_id', 'exam_name', 'student_id'], unique=True, sqlite_where=sa.text('deleted_at IS NULL'))

    op.create_table('course_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_class_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_course_students_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_class_id'], ['course_classes.id'], name=op.f('fk_course_students_course_class_id_course_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_course_students_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_students'))
    )
    with op.batch_alter_table('course_students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_students_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_students_course_class_id'), ['course_class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_students_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_students_student_id'), ['student_id'], unique=False)
        batch_op.create_index('uq_course_students_class_student', ['course_class_id', 'student_id'], unique=True, sqlite_where=sa.text('deleted_at IS NULL'))

    with op.batch_alter_table('homework', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_homework_course_id'), ['course_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_homework_course_id_courses'), 'courses', ['course_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homework', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_homework_course_id_courses'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_homework_course_id'))
        batch_op.drop_column('course_id')

    with op.batch_alter_table('course_students', schema=None) as batch_op:
        batch_op.drop_index('uq_course_students_class_student', sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_course_students_student_id'))
        batch_op.drop_index(batch_op.f('ix_course_students_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_course_students_course_class_id'))
        batch_op.drop_index(batch_op.f('ix_course_students_class_id'))

    op.drop_table('course_students')
    with op.batch_alter_table('course_scores', schema=None) as batch_op:
        batch_op.drop_index('uq_course_scores_exam_student', sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_course_scores_student_id'))
        batch_op.drop_index(batch_op.f('ix_course_scores_exam_name'))
        batch_op.drop_index(batch_op.f('ix_course_scores_exam_date'))
        batch_op.drop_index(batch_op.f('ix_course_scores_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_course_scores_course_id'))
        batch_op.drop_index(batch_op.f('ix_course_scores_class_id'))

    op.drop_table('course_scores')
    with op.batch_alter_table('course_classes', schema=None) as batch_op:
        batch_op.drop_index('uq_course_classes_course_class', sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_course_classes_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_course_classes_course_id'))
        batch_op.drop_index(batch_op.f('ix_course_classes_class_id'))

    op.drop_table('course_classes')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_deleted_at'))

    op.drop_table('courses')
    # ### end Alembic commands ###
