"""class roles and student records

Revision ID: db25d47805e4
Revises: e7b935f19602
Create Date: 2026-09-18 15:39:40.172428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db25d47805e4'
down_revision: Union[str, Sequence[str], None] = 'e7b935f19602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cadres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('student_name', sa.String(length=32), nullable=False),
    sa.Column('post', sa.String(length=32), nullable=False),
    sa.Column('term', sa.String(length=32), nullable=False),
    sa.Column('appraise', sa.String(length=8), nullable=False),
    sa.Column('duty', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_cadres_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_cadres_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cadres'))
    )
    with op.batch_alter_table('cadres', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cadres_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cadres_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cadres_student_id'), ['student_id'], unique=False)

    op.create_table('disciplines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('student_name', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('handling', sa.Text(), nullable=False),
    sa.Column('recorder', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_disciplines_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_disciplines_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disciplines'))
    )
    with op.batch_alter_table('disciplines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disciplines_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disciplines_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_disciplines_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_disciplines_student_id'), ['student_id'], unique=False)

    op.create_table('duty_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('weekday_no', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.String(length=8), nullable=False),
    sa.Column('group_name', sa.String(length=16), nullable=False),
    sa.Column('area', sa.String(length=16), nullable=False),
    sa.Column('leader_id', sa.Integer(), nullable=True),
    sa.Column('leader_name', sa.String(length=32), nullable=False),
    sa.Column('check', sa.String(length=8), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_duty_groups_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leader_id'], ['students.id'], name=op.f('fk_duty_groups_leader_id_students'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_duty_groups'))
    )
    with op.batch_alter_table('duty_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_duty_groups_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_duty_groups_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('student_name', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(length=32), nullable=False),
    sa.Column('apply_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_grants_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_grants_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grants'))
    )
    with op.batch_alter_table('grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grants_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grants_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_grants_student_id'), ['student_id'], unique=False)

    op.create_table('health_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('student_name', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('contact', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('emergency', sa.Text(), nullable=False),
    sa.Column('limit_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_health_records_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_health_records_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_records'))
    )
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_records_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_records_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_records_student_id'), ['student_id'], unique=False)
        batch_op.create_index('uq_health_records_student', ['class_id', 'student_id'], unique=True, sqlite_where=sa.text('student_id IS NOT NULL AND deleted_at IS NULL'))

    op.create_table('youth_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('student_name', sa.String(length=32), nullable=False),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.Column('branch', sa.String(length=64), nullable=False),
    sa.Column('post', sa.String(length=16), nullable=False),
    sa.Column('fee', sa.String(length=8), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_youth_members_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_youth_members_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_youth_members'))
    )
    with op.batch_alter_table('youth_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_youth_members_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_youth_members_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_youth_members_student_id'), ['student_id'], unique=False)

    op.create_table('duty_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duty_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('student_name', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['duty_id'], ['duty_groups.id'], name=op.f('fk_duty_members_duty_id_duty_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_duty_members_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_duty_members'))
    )
    with op.batch_alter_table('duty_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_duty_members_duty_id'), ['duty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_duty_members_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('duty_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_duty_members_student_id'))
        batch_op.drop_index(batch_op.f('ix_duty_members_duty_id'))

    op.drop_table('duty_members')
    with op.batch_alter_table('youth_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_youth_members_student_id'))
        batch_op.drop_index(batch_op.f('ix_youth_members_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_youth_members_class_id'))

    op.drop_table('youth_members')
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.drop_index('uq_health_records_student', sqlite_where=sa.text('student_id IS NOT NULL AND deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_health_records_student_id'))
        batch_op.drop_index(batch_op.f('ix_health_records_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_health_records_class_id'))

    op.drop_table('health_records')
    with op.batch_alter_table('grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grants_student_id'))
        batch_op.drop_index(batch_op.f('ix_grants_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_grants_class_id'))

    op.drop_table('grants')
    with op.batch_alter_table('duty_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_duty_groups_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_duty_groups_class_id'))

    op.drop_table('duty_groups')
    with op.batch_alter_table('disciplines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disciplines_student_id'))
        batch_op.drop_index(batch_op.f('ix_disciplines_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_disciplines_date'))
        batch_op.drop_index(batch_op.f('ix_disciplines_class_id'))

    op.drop_table('disciplines')
    with op.batch_alter_table('cadres', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadres_student_id'))
        batch_op.drop_index(batch_op.f('ix_cadres_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_cadres_class_id'))

    op.drop_table('cadres')
    # ### end Alembic commands ###
