"""partial unique indexes and seat hard delete

Revision ID: e3dfd6e7dd0e
Revises: 20daa5e4b541
Create Date: 2026-09-18 15:18:11.068386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3dfd6e7dd0e'
down_revision: Union[str, Sequence[str], None] = '20daa5e4b541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dorm_rooms', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_dorm_rooms_class_building_room'), type_='unique')
        batch_op.create_index('uq_dorm_rooms_class_building_room', ['class_id', 'building', 'room_no'], unique=True, sqlite_where=sa.text('deleted_at IS NULL'))

    with op.batch_alter_table('seats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seats_deleted_at'))
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DATETIME(), nullable=True))
        batch_op.create_index(batch_op.f('ix_seats_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('dorm_rooms', schema=None) as batch_op:
        batch_op.drop_index('uq_dorm_rooms_class_building_room', sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.create_unique_constraint(batch_op.f('uq_dorm_rooms_class_building_room'), ['class_id', 'building', 'room_no'])

    # ### end Alembic commands ###
