"""media student link

Revision ID: e7b935f19602
Revises: 2008dc6034ef
Create Date: 2026-09-18 15:33:03.911396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7b935f19602'
down_revision: Union[str, Sequence[str], None] = '2008dc6034ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_media_student_id'), ['student_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_media_student_id_students'), 'students', ['student_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_media_student_id_students'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_media_student_id'))
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###
