"""homework and homework_unsubmitted

Revision ID: ef77b90cc6e3
Revises: ab3a5f999d80
Create Date: 2026-09-18 14:21:11.394698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef77b90cc6e3'
down_revision: Union[str, Sequence[str], None] = 'ab3a5f999d80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homework',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('subject', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('deadline', sa.String(length=32), nullable=False),
    sa.Column('quality', sa.String(length=8), nullable=False),
    sa.Column('teacher', sa.String(length=32), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('rate_mode', sa.String(length=8), nullable=False),
    sa.Column('rate_manual', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_homework_class_id_classes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_homework'))
    )
    with op.batch_alter_table('homework', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_homework_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_homework_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('homework_unsubmitted',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('homework_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['homework_id'], ['homework.id'], name=op.f('fk_homework_unsubmitted_homework_id_homework'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_homework_unsubmitted_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_homework_unsubmitted')),
    sa.UniqueConstraint('homework_id', 'student_id', name='uq_homework_unsubmitted')
    )
    with op.batch_alter_table('homework_unsubmitted', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_homework_unsubmitted_homework_id'), ['homework_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_homework_unsubmitted_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homework_unsubmitted', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_homework_unsubmitted_student_id'))
        batch_op.drop_index(batch_op.f('ix_homework_unsubmitted_homework_id'))

    op.drop_table('homework_unsubmitted')
    with op.batch_alter_table('homework', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_homework_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_homework_class_id'))

    op.drop_table('homework')
    # ### end Alembic commands ###
